import dbConnect from '@/lib/mongodb';
import User from '@/models/User';
import AdminKey from '@/models/AdminKey';
import { Users, UserPlus, Key, Trash2, ShieldCheck, Mail, Clock, Activity, Zap, Shield } from 'lucide-react';
import { cookies } from 'next/headers';
import GenerateSubKeyButton from '@/components/GenerateSubKeyButton';

export const dynamic = 'force-dynamic';

export default async function TeamPage() {
  await dbConnect();

  const authCookie = cookies().get('admin_auth')?.value || '';
  const parts = authCookie.split('|');
  const role = parts[0];
  const plan = parts[1];
  const adminKeyString = parts[3] || '';

  // Only Enterprise or SuperAdmin can access this
  if (plan !== 'Enterprise' && role !== 'superadmin') {
    return (
      <div className="flex flex-col items-center justify-center min-h-[60vh] text-center px-10">
         <Shield className="text-red-500 mb-6" size={64} />
         <h1 className="text-3xl font-black text-white uppercase italic tracking-tighter">Acesso Restrito</h1>
         <p className="text-slate-500 text-xs font-bold uppercase tracking-widest mt-4">Apenas contas de nível Enterprise podem gerenciar equipes.</p>
      </div>
    );
  }

  // Get the owner's AdminKey record to check sub-key limits
  const ownerKeyRecord = await AdminKey.findOne({ key: adminKeyString });
  
  // Get members (Users who registered with a sub-key from this owner)
  const members = await User.find({ ownerKey: adminKeyString });

  // Get all sub-keys generated by this owner
  const subKeys = await AdminKey.find({ ownerId: adminKeyString, isSubKey: true }).sort({ createdAt: -1 });

  return (
    <div className="space-y-12 max-w-[1500px] mx-auto pb-40 animate-in fade-in duration-1000">
      
      {/* HEADER AREA */}
      <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-10 bg-[#050505] p-12 rounded-[3rem] border border-white/5 shadow-2xl relative overflow-hidden">
        <div className="absolute top-0 right-0 w-96 h-96 bg-purple-600/[0.03] blur-[120px] pointer-events-none" />
        
        <div className="flex items-center gap-8 relative z-10">
          <div className="w-20 h-20 rounded-[2rem] bg-purple-600/[0.02] flex items-center justify-center border border-purple-500/10 shadow-[inset_0_0_20px_rgba(139,92,246,0.05)] group hover:border-purple-500/30 transition-all duration-500">
            <Users className="text-purple-500" size={36} />
          </div>
          <div>
            <h1 className="text-4xl font-black text-white tracking-tighter uppercase leading-none italic">EQUIPE <span className="text-purple-600 italic">ENTERPRISE</span></h1>
            <p className="text-[10px] text-slate-500 uppercase tracking-[0.6em] font-black mt-4">Gestão de Colaboradores e Licenças Internas</p>
          </div>
        </div>
        
        <div className="relative z-10">
          <GenerateSubKeyButton 
            ownerKey={adminKeyString} 
            maxSubKeys={ownerKeyRecord?.maxSubKeys || 0} 
            generatedCount={ownerKeyRecord?.generatedSubKeys || 0}
          />
        </div>
      </div>

      {/* STATS */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
        <div className="bg-white/[0.01] p-10 rounded-[2.5rem] border border-white/5 shadow-xl transition-all hover:scale-[1.02] duration-500">
            <p className="text-[10px] text-slate-500 uppercase font-black tracking-[0.4em] mb-6">MEMBROS ATIVOS</p>
            <div className="flex items-end justify-between">
              <h3 className="text-6xl font-black text-white italic tracking-tighter leading-none">{members.length}</h3>
              <div className="p-4 bg-white/[0.02] rounded-2xl border border-white/5 text-purple-500">
                <ShieldCheck size={24} />
              </div>
            </div>
        </div>
        <div className="bg-purple-500/[0.01] p-10 rounded-[2.5rem] border border-white/5 shadow-xl transition-all hover:scale-[1.02] duration-500">
            <p className="text-[10px] text-purple-500 uppercase font-black tracking-[0.4em] mb-6">KEYS DISPONÍVEIS</p>
            <div className="flex items-end justify-between">
              <h3 className="text-6xl font-black text-white italic tracking-tighter leading-none">{(ownerKeyRecord?.maxSubKeys || 0) - (ownerKeyRecord?.generatedSubKeys || 0)}</h3>
              <div className="p-4 bg-white/[0.02] rounded-2xl border border-white/5 text-purple-500">
                <Key size={24} />
              </div>
            </div>
        </div>
        <div className="bg-white/[0.01] p-10 rounded-[2.5rem] border border-white/5 shadow-xl transition-all hover:scale-[1.02] duration-500">
            <p className="text-[10px] text-slate-500 uppercase font-black tracking-[0.4em] mb-6">CAPACIDADE TOTAL</p>
            <div className="flex items-end justify-between">
              <h3 className="text-6xl font-black text-white italic tracking-tighter leading-none">{ownerKeyRecord?.maxSubKeys || 0}</h3>
              <div className="p-4 bg-white/[0.02] rounded-2xl border border-white/5 text-slate-700">
                <Activity size={24} />
              </div>
            </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-12">
        
        {/* MEMBERS LIST */}
        <div className="bg-[#050505] rounded-[3rem] border border-white/5 shadow-2xl overflow-hidden backdrop-blur-3xl">
          <div className="px-12 py-10 border-b border-white/5 flex items-center justify-between">
            <h2 className="text-xl font-black text-white tracking-tighter uppercase leading-none italic">STAFF <span className="text-purple-600 italic">ONBOARD</span></h2>
            <p className="text-[9px] text-slate-700 uppercase tracking-widest font-black mt-2">Membros da Equipe</p>
          </div>
          <div className="p-4 space-y-4">
            {members.length === 0 ? (
                <div className="py-20 text-center opacity-10 flex flex-col items-center">
                    <Users size={48} className="mb-4" />
                    <p className="text-xs font-black uppercase tracking-widest">Nenhum membro cadastrado</p>
                </div>
            ) : (
                members.map((member: any) => (
                    <div key={member._id.toString()} className="flex items-center justify-between p-6 bg-white/[0.01] rounded-3xl border border-white/5 hover:border-purple-500/20 transition-all group">
                        <div className="flex items-center gap-6">
                            <div className="w-12 h-12 bg-purple-600/10 rounded-2xl flex items-center justify-center text-purple-500 border border-purple-500/20">
                                <UserPlus size={20} />
                            </div>
                            <div>
                                <h4 className="text-sm font-black text-white uppercase tracking-tight italic">{member.username}</h4>
                                <div className="flex items-center gap-3 mt-1">
                                    <span className="text-[9px] font-bold text-slate-600 uppercase tracking-widest">{member.email || 'SEM EMAIL'}</span>
                                    <div className="w-1 h-1 rounded-full bg-slate-800" />
                                    <span className="text-[9px] font-black text-purple-500/50 uppercase tracking-widest">{member.role}</span>
                                </div>
                            </div>
                        </div>
                        <button className="p-3 bg-white/[0.02] hover:bg-red-500/10 text-slate-700 hover:text-red-500 rounded-xl transition-all opacity-0 group-hover:opacity-100">
                            <Trash2 size={16} />
                        </button>
                    </div>
                ))
            )}
          </div>
        </div>

        {/* KEYS LIST */}
        <div className="bg-[#050505] rounded-[3rem] border border-white/5 shadow-2xl overflow-hidden backdrop-blur-3xl">
          <div className="px-12 py-10 border-b border-white/5 flex items-center justify-between">
            <h2 className="text-xl font-black text-white tracking-tighter uppercase leading-none italic">KEYS DE <span className="text-purple-600 italic">ACESSO</span></h2>
            <p className="text-[9px] text-slate-700 uppercase tracking-widest font-black mt-2">Licenças Geradas</p>
          </div>
          <div className="p-4 space-y-4">
            {subKeys.length === 0 ? (
                <div className="py-20 text-center opacity-10 flex flex-col items-center">
                    <Key size={48} className="mb-4" />
                    <p className="text-xs font-black uppercase tracking-widest">Nenhuma key gerada</p>
                </div>
            ) : (
                subKeys.map((k: any) => (
                    <div key={k._id.toString()} className="flex items-center justify-between p-6 bg-white/[0.01] rounded-3xl border border-white/5 hover:border-purple-500/20 transition-all group">
                        <div className="flex items-center gap-6">
                            <div className="w-12 h-12 bg-white/[0.02] rounded-2xl flex items-center justify-center text-slate-500 border border-white/5 group-hover:border-purple-500/30 transition-all">
                                <Key size={20} />
                            </div>
                            <div>
                                <h4 className="font-mono text-sm font-black text-white tracking-wider">{k.key}</h4>
                                <div className="flex items-center gap-3 mt-1">
                                    <span className={`text-[9px] font-black uppercase tracking-widest ${k.usedBy ? 'text-red-500/50' : 'text-emerald-500'}`}>
                                        {k.usedBy ? `USADO POR: ${k.usedBy}` : 'DISPONÍVEL'}
                                    </span>
                                    <div className="w-1 h-1 rounded-full bg-slate-800" />
                                    <span className="text-[9px] font-bold text-slate-700 uppercase tracking-widest">{new Date(k.createdAt).toLocaleDateString()}</span>
                                </div>
                            </div>
                        </div>
                    </div>
                ))
            )}
          </div>
        </div>

      </div>
    </div>
  );
}
